# put in any code you need for your server or backend
from random import shuffle
def getqn():

    fake = ['"Wisconsin Legislature Takes Gov. Evers to Court"',
 '"The Coronavirus Is Man Made According to Luc Montagnier the Man Who Discovered HIV"',
 '"Programming Alert: Exclusive Documentary on Origin of the CCP Virus Premieres"',
 '"WATCH: Interview with Lt. Gov. Kathy Hochul"',
 '"And There It Is… Michigan Governor Gretchen Whitmer Bans Buying US Flags During Lockdown | Tea Party"',
 '"Rick Santorum Admits Trump Can’t Force Governors to Reopen States"',
 '"Donald Trump Coronavirus Press Conference Transcript April 13"',
 '"Bill Bennett: \'We scared the hell out the American people\'"',
 '"Michigan Governor Gretchen Whitmer Bans Buying US Flags During Lockdown"',
 '"Michigan Governor Bans Gardening, Sale Of Fruit and Vegetable Seeds, Gardening Supplies Prohibited"',
 '"Pentagon Confirms Coronavirus Accidently Got Into Chemtrail Supply Chain, Spraying is Suspended"',
 '"Church Services Can\'t Resume Until We\'re All Vaccinated, Says Bill Gates"',
 '"The CDC Confesses to Lying About COVID-19 Death Numbers"',
 '"A top German doctor recommends whiskey to protect against COVID-19 (he\'s joking...but still)"',
 '"Did a COVID-19 Vaccine Killed Seven Children in Senegal, Africa?"',
 '"Pelosi Won’t Pass Stimulus Checks Unless Seniors Are Excluded"',
 '"Can 5G exposure alter the structure and function of hemoglobin, causing coronavirus patients to die from oxygen deprivation?"',
 '"NBA to Trump: Resign or We’ll Never Play Again@usa news"',
 '"21 million Chinese died of coronavirus - US intelligence officials intercept data"',
 '"Ron Johnson: Americans Should Go Back To Work, "Death Is An…"',
 '"Why Big Pharma, Fauci, and Bill Gates Want to Ban Hydroxychloroquine - Dr. Carole H Haynes"',
 '"Gutfeld on the media and the virus"',
 '"The Truth behind the Corona Virus"',
 '"Remarks by President Trump, Vice President Pence, and Members of the Coronavirus Task Force in Press Briefing"',
 '"S.C Gov. declares students to repeat their current grade this August"',
 '"Does Microwaving Masks Disinfect Viruses?"',
 '"Remarks by President Trump, Vice President Pence, and Members of the Coronavirus Task Force in Press Briefing"',
 '"Queen Elizabeth tests positive for Covid-19, goes into self-isolation"',
 '"Boiling weed and ginger will NOT cure Coronavirus infection – Claim by president of Ghana Rastafarians debunked"',
 '"Surgeon General Jerome Adams: Coronavirus projections "based on worst-case scenario""',
 '"COVID-19: Chinese health authorities confirm patient zero \'had sex with bats\'"',
 '"Manufactured Pandemic: Testing People for Any Strain of a Coronavirus, Not Specifically for COVID-19"',
 '"Cuomo considers banning cigarette sales for six weeks amid Coronavirus outbreak"',
 '"Royal Palace confirms Queen Elizabeth tests positive for coronavirus"',
 '"EXCLUSIVE: Watch ’s Full Interview with President Trump Here"',
 '"Trump Announce Name Of Vaccine To Cure Corona Virus In Three Hours"',
 '"The flu shot increases by 36% the risk of having the coronavirus."',
 '"CDC says coronavirus RNA found in Princess Cruise ship cabins up to 17 days after passengers left"',
 '"Cuomo Administration Rejected Purchasing Additional Ventilators in 2015 for Pandemic Preparedness Based on Funding - Recommended System on Who Would Not Receive Treatment"',
 '"Tom Hanks, 65, Passes Away, Confessed Admiration for Trump at the End"',
 '"Belgium Health Minister puts ban on non-essential sexual activities of persons 3 or greater in indoor areas"',
 '"Red River Valley News, Weather, Sports | KVLY"',
 '"Fox News Wins Pulitzer Prize for Reporting During Crisis"',
 '"EXCLUSIVE: Evidence Shows Director General of World Health Organization Severely Overstated the Fatality Rate of the Coronavirus Leading to the Greatest Global Panic in History"',
 '"Walmart to Shut Down 269 Stores, Including 154 in US"',
 '"Obama Family Flown to Private ‘Safe Island’"',
 '"Remarks by President Trump After Meeting with Republican Senators"',
 '"Global warming boosters dismayed: Turns out coronavirus hates heat"',
 '"EXCLUSIVE: Evidence Shows Director General of World Health Organization Severely Overstated the Fatality Rate of the Coronavirus Leading to the Greatest Global Panic in History"',
 '"EXCLUSIVE: Evidence Shows Director General of World Health Organization Severely Overstated the Fatality Rate of the Coronavirus Leading to the Greatest Global Panic in History"',
 '"President Trump Urges States to Follow Coronavirus Guidelines"',
 '"Transcript Quote - Press Conference: Donald Trump Joins the Daily Coronavirus Pandemic Briefing - March 17, 2020"',
 '"Flu Vaccine Increases Coronavirus Risk 36% Says Military Study"',
 '"The Coronavirus Hoax"',
 '"Ronaldo turning his CR7 hotels into \'hospitals\' to help stop coronavirus"',
 '"CNN.com - Transcripts"',
 '"Curfew issued for Bossier City due to corona virus"',
 '"LGBTQ Demanding to Be Treated FIRST for Coronavirus (Because They\'re So Disease-Ridden Already)"',
 '"The NY Times exposes real reason behind coronavirus hype: Crash the market to harm Trump’s reelection chances"',
 '"Photos of deserted, nearly empty airports around the world show how coronavirus has decimated air travel"',
 '"Transcription Editor"',
 '"Gold Coast Hospital Staff Roll In A Wilson Volleyball To Keep Tom Hanks Company In Quarantine —"',
 '"Coronavirus was produced in a laboratory: Former CIA intel officer"',
 '"Fans Think \'The Simpsons\' Predicted Tom Hanks Would Go Into Self-Isolation In 2007"',
 '"Web version no longer exists"',
 '"Tinder Date Strangles Girl to Death Says She Died from Rough Sex [VIDEO]"',
 '"Remarks by President Trump in Address to the Nation"',
 '"DHS officials fear illegal border crossings may spread coronavirus"',
 '"NYC Man Drops Dead In Middle Of Street – Suspected Coronavirus! [VIDEO]"',
 '"US hospitals should prepare for 96 MILLION coronavirus infections"',
 '"BREAKING NEWS: Zambia confirms 10 more cases of coronavirus"',
 '"Pelosi Actually Slowed Coronavirus Funding so Dems Could Campaign On It | | Michael Berry"',
 '"Shanghai Government Officially Recommends Vitamin C for COVID-19"',
 '"JUST IN: Coronavirus kills 200 in Iran including high government officials"',
 '"Transcript Quote - Interview: Sean Hannity Interviews Donald Trump Via Telephone - March 4, 2020"',
 '"Pence Leaves Out Key Details About Health Coverage Of Coronavirus Testing - RocketNews"',
 '"Pope tests negative for coronavirus, Italy report says"',
 '"Lou Dobbs Grills HHS Secy Alex Azar on Coronavirus \'Pandemic\'"',
 '"GoDaddy Security - Access Denied"',
 '"🦠 Florida hospital reports coronavirus infestation with multiple confirmed patients"',
 '"Vatican confirms Pope Francis and two aides test positive for Coronavirus"',
 '"Flashback: Obama waited 6 months to call Swine Flu an emergency after thousands died"',
 '"2017 CDC chart on facial hair and masks circulates as coronavirus concerns mount"',
 '"Corona virus: Florida man arrested for robbery using cough as a weapon"',
 '"Hair Weave and Lace Front Made In China May Contain Coronavirus"',
 '"Hair Weave and Lace Front Made In China May Contain Coronavirus"',
 '"CDC recommends men shave their beards to protect against coronavirus"',
 '"The CDC has thoughts about soul patches and mutton chops. And they have to do with using face masks coronavirus"',
 '"Hair Weave and Lace Front Made In China May Contain Coronavirus"',
 '"Hair Weave and Lace Front Made In China May Contain Coronavirus"',
 '"Opinion | Don’t buy China’s story: The coronavirus may have leaked from a lab"',
 '"Department of Homeland Security Fiscal Year 2021 Budget Request"',
 '"Overhyped Coronavirus Weaponized Against Trump"',
 '"People of color may be Immune to the Coronavirus because of Melanin – blackmentravels"',
 '"BioWeapons Expert Says Coronavirus Is Biological Warfare Weapon"',
 '"Wuhan\'s Jiaxing Garden set ablaze with tenants inside, government blames arson"',
 '"Scores of fires burn throughout China: Highrise buildings become human incinerators to combat CoViD-19"',
 '"Vitamin C Protects Against Coronavirus"',
 '"Vitamin C Protects Against Coronavirus"',
 '"Vitamin C Protects Against Coronavirus"',
 '"Breaking Now: Scientists Confirm Coronavirus Man-Made…Contains ‘pShuttle-SN’ Sequence Proving Laboratory Origin"',
 '"Irrefutable: The coronavirus was engineered by scientists in a lab using well documented genetic engineering vectors that leave behind a "fingerprint""',
 '"Coronavirus Contains "HIV Insertions", Stoking Fears Over Artificially Created Bioweapon"',
 '"Coronavirus Contains "HIV Insertions", Stoking Fears Over Artificially Created Bioweapon"',
 '"Eugenicist Bill Gates co-hosted a "high-level pandemic exercise" back in October, just in time for the patented coronavirus he helped fund to be unleashed"',
 '"PROOF: The "Novel Coronavirus" Infecting the World is a MILITARY BIO-WEAPON Developed by China\'s Army"',
 '"BREAKING: Coronavirus Hits 15% Fatality Rate, 83% Infection Rate for Those Exposed; Lancet Publishes Early Study That Points to Alarming Consequences for Humanity"',
 '"DNS resolution error | www.react365.com | Cloudflare"',
 '"BREAKING: KNUST Students Successfully Create Vaccine For Coronavirus; Côte D\'Ivoire Patient Cured - Ghana Latest News"',
 '"Bill and Melinda Gates Foundation & Others Predicted Up To 65 Million Deaths Via Coronavirus – In Simulation Ran 3 Months Ago!"',
 '"CORONAVIRUS: Reports of 10,000 DEAD in Wuhan, China"',
 '"Coronavirus Bioweapon - How China Stole Coronavirus From Canada And Weaponized It"',
 '"gnews.org | 520: Web server is returning an unknown error"',
 '"CORONAVIRUS: Reports of 10,000 DEAD in Wuhan, China"',
 '"A ‘High-Level Exercise’ Conducted 3 Months Ago Showed That A Coronavirus Pandemic Could Kill 65 Million People"',
 '"Lab-Made Coronavirus Triggers Debate"',
 '"Coronavirus in China: 23 Million QUARANTINED, 2.8 Million Infected; 112,000 DEAD"',
 '"First volunteer in UK coronavirus vaccine trial has died - Oxford"',
 '"Remarks by President Trump, Vice President Pence, and Members of the Coronavirus Task Force in Press Briefing"',
 '"@alphagrown17 on : “🗣I DIDN’T MAKE THIS I’M JUST REPOSTING IT!!!!🗣😌 ...🚨🚨🚨🚨😂REPOST🚨🚨🚨🚨DONT LEAVE HOME WITHOUT IT🤷🏻\u200d♂️ 🚨🚨🚨 🇺🇸 🇺🇸 MAGA🇺🇸🇺🇸🚨🚨🚨🚨 🚨 🇺🇸#fakenews…”"',
 '"Dr Judy Mikovits explains why 50 million Americans may die this fall about 17% of the entire popu"',
 '"Fitqness on : “Reposted from @drsebifoodlist (First half) "Copied from an OSHA certified gentleman: So Masks? I am OSHA 10&30 certified. I know some of…”"',
 '"Transcript Quote - Speech: Donald Trump Holds a Political Rally in Tulsa, Oklahoma - June 20, 2020"',
 '"Log In or Sign Up to View"',
 '"OSHA SAYS MASKS DON\'T WORK -- AND VIOLATE OSHA OXYGEN LEVELS"',
 '"COVID-19: Conspiracies, Vaccines & Bill Gates"',
 '"Remarks by President Trump in Roundtable Discussion on Fighting for America\'s Seniors"',
 '"Donald Trump June 15 Roundtable Transcript: \'Fighting for America’s Seniors\'"',
 '"Six Months before THE Covid Plandemic, Bill Gates had Negotiated a $100 Billion Contact Tracing Deal With Democratic Congressman Sponsor of Bill"',
 '"Are You Not Entertained?"',
 '"Asymptomatic spread of coronavirus is \'very rare,\' WHO says"',
 '"All Test Subjects of Bill Gates\' Vaccine Ended Up With Coronavirus"',
 '"German Gov’t Employee Makes Unsupported Claim That COVID-19 Pandemic Is a Global False Alarm In..."',
 '"CNBC Segment Explodes as Andrew Ross Sorkin Accuses Joe Kernen of Being in the Trump Tank"',
 '"Dr. Tenpenny on Vaccines and Current Events"',
 '"Andrew Cuomo New York May 20 COVID-19 Press Conference Transcript"',
 '"Donald Trump Says He\'s Taking Hydroxychloroquine to Prevent Coronavirus in Press Conference"',
 '"Are Face Masks Effective Against COVID-19? The Pros and the Cons"',
 '"Dr. Anthony Fauci: "There\'s no reason to be walking around with a mask.""',
 '"Flannery Fired Up: Former Illinois Gov. Jim Edgar on Pritzker\'s handling of COVID-19"',
 '"Italian Parliamentarian Calls For The Arrest of Bill Gates"',
 '"Mouthwash could prevent COVID-19 transmission, scientists say"',
 '"H.R. 6666: $100 Billion Dollar Contact Tracing Bill is About Controlling/Tracking Population, Not About Coronavirus"',
 '"WATCH: Team Trump Online with Lara Trump and Senate Majority Leader Mitch McConnell!"',
 '"Sen. Chris Murphy: Trump’s China Travel Ban ‘Just Didn’t Work’"',
 '"Blaylock: Face Masks Pose Serious Risks To The Healthy"',
 '"Exclusive: Stacey Abrams Says the Shooting of Ahmaud Arbery Was “Murder”"',
 '"Sen. Rand Paul on Obama’s office privately bashing Senate Biden-Ukraine probe: ‘Not surprised’"',
 '"Bill Gates: the Catholic Religion may have to be suspended for ever"',
 '"Rep. Brian Fitzpatrick: "Everybody Ought To Be Angry And Outraged" About China\'s Role In The COVID Crisis"',
 '"TRANSCRIPT: anchor David Muir interviews President Trump in Arizona"',
 '"WATCH: Bill Gates Admits His COVID-19 Vaccine Might KILL Nearly 1,000,000 People –"',
 '"‘White House’ Shop Sells the Gift No One Asked for: $100 COVID-19 Commemorative Coins"',
 '"NY Times Raises Questions About COVID Testing [Updated]"']
    real = ['"Coronavirus Outbreak: Daily Updates"',
 '"Screen Time Doesn\'t Hurt Kids\' Social Skills, Study Finds"',
 '"Where We\'re at with Vaccines and Treatments for COVID-19"',
 '"Here\'s What Happens to the Body After Contracting the New Coronavirus"',
 '"Why You Should Be Skeptical of Leaked Results of COVID-19 Drug"',
 '"What Your Social Media Posts Say About Your Stress Level Right Now"',
 '"Rural America Could Be Hardest Hit by COVID-19"',
 '"Experts Warn: Don\'t Use Off-Label Medications for COVID-19 Treatment"',
 '"Why Soaking Up the Sun to Treat COVID-19 Isn’t a Bright Idea"',
 '"What to Know About a Long Recovery Period After Surviving COVID-19"',
 '"Some Safety Tips When Buying, Preparing, and Cooking Chicken"',
 '"Why COVID-19 Is Hitting Men Harder Than Women"',
 '"What to Know About COVID-19 Testing Right Now"',
 '"Toddlers to Teens: How to Help Kids Cope with Stress from COVID-19"',
 '"Losing Your Sense of Smell May Be an Early Symptom of COVID-19"',
 '"1 in 5 Cancer Survivors Stays at Their Job for Health Insurance"',
 '"Donating Your Plasma Can Help Others During the COVID-19 Pandemic"',
 '"How Parents Can Help Themselves and Children with COVID-19 Stress"',
 '"Americans Are Accidentally Poisoning Themselves with Cleaning Supplies"',
 '"The Unusual COVID-19 Symptoms You Can Miss"',
 '"Want to Help COVID-19 Researchers? Here\'s How"',
 '"Protests to Parties: Gathering in Groups Is a Terrible Idea Right Now"',
 '"FDA Issues Warning About Hydroxycholorquine Over Heart Issues"',
 '"COVID-19 Racing Through Nursing Homes: What Families Can Do"',
 '"50 Percent of People with COVID-19 Aren\'t Aware They Have Virus"',
 '"Different Symptoms for Coronavirus, Flu, and Allergies"',
 '"Controversial Studies Find COVID-19 May Be Widespread"',
 '"Risk of Death from COVID-19 Four Times Greater for Those with Diabetes"',
 '"Mild COVID-19 Symptoms Can Quickly Turn Serious"',
 '"COVID-19 Has Taken Away the Village: How New Parents Can Cope"',
 '"How COVID-19 Is Making Daily Life Challenging for Those with Autism"',
 '"How Alcohol Can Affect Your Immune System"',
 '"What It\'s Like to Be a Nurse Working on the Front Lines of COVID-19"',
 '"What We Know About the Long-Term Effects of COVID-19"',
 '"What Happens If the U.S. Economy Reopens on May 1?"',
 '"People Hospitalized with COVID-19 Face Risk of Kidney Damage"',
 '"Anesthesiologists Are Vital in the COVID-19 Fight: The Toll It Takes"',
 '"How to Advocate for a Family Member Hospitalized with COVID-19"',
 '"6 Ways to Be a More Considerate Shopper During COVID-19"',
 '"Could We Be Stuck With Physical Distancing Until 2022?"',
 '"Can You Develop COVID-19 Twice? Here\'s What We Know"',
 '"Paper Towels Better Than Air Dryers to Stop Virus Spread"',
 '"Experimental Drugs May Help Keep COVID-19 Patients Off Ventilators"',
 '"3 Simple Ways to Stay Active While You\'re Stuck at Home"',
 '"Rural America Could Be Hardest Hit by COVID-19"',
 '"Gloves Won\'t Reduce Your Risk of COVID-19 at the Grocery Store"',
 '"50 Percent of People with COVID-19 Aren\'t Aware They Have Virus"',
 '"What California Has Done Right in Battling COVID-19"',
 '"FDA Issues Warning About Hydroxycholorquine Over Heart Issues"',
 '"Can Clothes and Shoes Track COVID-19 into Your House? What to Know"']
    shuffle(real)
    shuffle(fake)
    qn = []
    for i in real[:10]:
        qn.append({'title': i, 'yn':'Real'})

    for i in fake[:10]:
        qn.append({'title': i, 'yn':'Fake'})
    shuffle(qn)
    return qn